# Generated by Django 6.0.1 on 2026-03-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('paginas', models.IntegerField()),
                ('editorial', models.CharField(max_length=150)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
