# Generated by Django 6.0.1 on 2026-02-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaApiMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('especie', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_de_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mascota_api_mascota',
                'managed': False,
            },
        ),
    ]
